eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9000/eureka
server:
    port: 8082
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes: '[{id=service_product, uri=lb://productms, predicates=[Path= /products/**]},
                {id=service_customer, uri=lb://customerms, predicates=[Path= /customers/**]}]'
